"""
TODO
1. Write a method that, given a trained expert, generates and saves (state/action) pairs
generated by the expert
"""

import argparse
from expert_train import get_mt10_env, set_seed, evaluate_agent
from soft_actor_critic import SAC, ReplayMemory


def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument('--env-index', default=0, type=int,
                        help='Index of the MT10 environment to train on')
    parser.add_argument('--checkpoint', default='expert/checkpoints/sac_checkpoint_reach-v2_best',
                        help='Path to saved train run info')
    parser.add_argument('--render', action="store_true",
                        help='Render evaluation episodes (default: False)')
    parser.add_argument('--n_samples', default=1000000, type=int,
                        help='Number of state/action pairs to sample from the expert')
    return parser.parse_args()


if __name__ == "__main__":
    pass
